name = "willow-sage-wedding"
pages_build_output_dir = "dist"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "brink-wedding-db"
# Run 'npx wrangler d1 info brink-wedding-db' to get your specific ID and paste it below
database_id = "77263095-2f5d-4fe2-a04a-d448a2af5054"
